[
    { "code": "AHS", "name": "Arkansas Hot Springs National Park Network", "GWWMapType": 4 },
    { "code": "ANC", "name": "Arkansas Natural Resources Commission Groundwater Network", "GWWMapType": 4 },
    { "code": "ANL", "name": "Arkansas northern Lonoke County Groundwater Network", "GWWMapType": 4 },
    { "code": "ASR", "name": "Arkansas Sparta Recovery Groundwater Network", "GWWMapType": 4 },
    { "code": "CGW", "name": "Connecticut Groundwater Network", "GWWMapType": 4 },
    { "code": "CSC", "name": "Chesterfield County, SC Groundwater Network", "GWWMapType": 4 },
    { "code": "CWN", "name": "Catawba-Wateree Groundwater Network", "GWWMapType": 4 },
    { "code": "GAD", "name": "Georgia Albany Dougherty County Groundwater Level Network", "GWWMapType": 4 },
    { "code": "GAR", "name": "Georgia Augusta Richmond County Groundwater Level Network", "GWWMapType": 4 },
    { "code": "GBG", "name": "Georgia Brunswick Glynn County Groundwater Level Network", "GWWMapType": 4 },
    { "code": "GCN", "name": "Georgia Continuous Groundwater Level Networks", "GWWMapType": 4 },
    { "code": "GLV", "name": "Georgia Lawrenceville Groundwater Level Network", "GWWMapType": 4 },
    { "code": "HCN", "name": "Hamilton County, Indiana Groundwater Network", "GWWMapType": 4 },
    { "code": "IDM", "name": "Indiana Department of Environmental Management Groundwater Network", "GWWMapType": 4 },
    { "code": "IDN", "name": "Indiana Department of Natural Resources Groundwater Network", "GWWMapType": 4 },
    { "code": "IDV", "name": "Indiana Department of Natural Resources Voluntary Groundwater Network", "GWWMapType": 4 },
    { "code": "IGN", "name": "Illinois Groundwater Level Network", "GWWMapType": 4 },
    { "code": "ISJ", "name": "St. Joseph County, Indiana Groundwater Network", "GWWMapType": 4 },
    { "code": "LCC", "name": "Louisiana Capital Area Groundwater Conservation Commission Level Network", "GWWMapType": 4 },
    { "code": "LNR", "name": "Louisiana Department of Natural Resources Groundwater Level Network", "GWWMapType": 4 },
    { "code": "LTD", "name": "Louisiana Department of Transportation and Development Level Network", "GWWMapType": 4 },
    { "code": "LTN", "name": "Long-Term Groundwater Data Network", "GWWMapType": 3 },
    { "code": "MAL", "name": "Memphis Area Groundwater-Level Network", "GWWMapType": 9 },
    { "code": "MBN", "name": "Mesilla Basin Observation Well Network, New Mexico", "GWWMapType": 9 },
    { "code": "MBT", "name": "Minnesota Bemidji Toxics Oil Spill Research Site Network", "GWWMapType": 4 },
    { "code": "MUS", "name": "Minnesota Upper Sioux Community Groundwater Monitoring Network", "GWWMapType": 4 },
    { "code": "NCG", "name": "Nebraska Continuous Groundwater Level Network", "GWWMapType": 4 },
    { "code": "NEN", "name": "New England Groundwater Network", "GWWMapType": 8 },
    { "code": "NHV", "name": "New Hampshire and Vermont Groundwater Level Network", "GWWMapType": 8 },
    { "code": "NJN", "name": "New Jersey Groundwater Level Network", "GWWMapType": 6 },
    { "code": "NNR", "name": "Nebraska's Natural Resource Districts", "GWWMapType": -1 },
    { "code": "PAN", "name": "Philadelphia Area Groundwater Level Network", "GWWMapType": 4 },
    { "code": "PIC", "name": "Colorado Piceance Groundwater Network, Rio Blanco County", "GWWMapType": 4 },
    { "code": "PRB", "name": "Potomac River Basin", "GWWMapType": 4 },
    { "code": "SCB", "name": "Southern California Basin Network", "GWWMapType": -1 },
    { "code": "TGN", "name": "Tennessee Groundwater Network", "GWWMapType": -1 }
]